language: node_js
node_js:
  - "8"
before_install:
  cd docs && npm install && cd ../
before_script:
  npm run compile && npm run lint
after_success: npm run coverage
before_deploy:
  cd docs && npm run build && cd ../ && npm run build:travis && zip -r build.zip anchor-ui
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/build
  email: ian.stewart@anchor.chat
  name: IanCStewart
  on:
    branch: master
  provider: releases
  api_key: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  file: ""
  skip_cleanup: true
  on:
    tags: true
notifications:
  email: false
