language: node_js
node_js:
  - "8"
before_install:
  cd docs && npm install && cd ../
before_script:
  npm run compile && npm run lint
after_success: ./node_modules/.bin/codecov --file=./coverage/lcov.info
before_deploy:
  cd docs && npm run build && cd ../
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: docs/build
  email: ian.stewart@anchor.chat
  name: IanCStewart
  on:
    branch: master
notifications:
  email: false
